version: '3.0'

# this docker file builds 2 wordpress websites:
# vasulka.cz and tcoil.info
# each site has its own database

# source paths to files or directories
# are relative to location of docker.compose.yaml file

services:

 wordpress_www0:
    image: wordpress
    links:
     - mariadb_vasulka_cz:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "8080:80"
    volumes:
     - ./html_vasulka_cz:/var/www/html
    restart: always

 wordpress_www1:
    image: wordpress
    container_name: wordpress_tcoil_info
    links:
     - mariadb_tcoil_info:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "8081:80"
    volumes:
     - ./html_tcoil_info:/var/www/html
    restart: always 

 mariadb_vasulka_cz:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE_0=wordpress_vasulka_cz
    volumes:
     - ./database_vasulka_cz:/var/lib/mysql
    restart: always 

 mariadb_tcoil_info:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE_1=wordpress_tcoil_info
    volumes:
     - ./database_tcoil_info:/var/lib/mysql
    restart: always 