version: '3.7'

# this docker file builds 2 wordpress websites:
# vasulka.cz and tcoil.info
# each site has its own database

# source paths to files or directories
# are relative to location of docker.compose.yaml file

services:

 wordpress_www0:
    image: wordpress
    links:
     - mariadb_www0:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "8080:80"
    volumes:
     - ./html_www0:/var/www/html
    restart: always

 wordpress_www1:
    image: wordpress
    container_name: wordpress_www1
    links:
     - mariadb_www1:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "8081:80"
    volumes:
     - ./html_www1:/var/www/html
    restart: always 

 mariadb_www0:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE_0=wordpress_www0
    volumes:
     - ./database_www0:/var/lib/mysql
    restart: always 

 mariadb_www1:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE_1=wordpress_www1
    volumes:
     - ./database_www1:/var/lib/mysql
    restart: always 